name: Auto- approve and merge dependabot PRs if the build passes and its minor or patch version update
on: pull_request_target
permissions: write-all
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Auto-approve and merge dependabot PRs with patch version
        uses: bring/github-actions/.github/actions/auto-merge-dependabot-prs@master
        with:
          semver_update_type: minor
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
